DATA:
  data_name: s3dis 
  d_in_initial: 4 # feat dim color + height 
  d_out_initial: 80  # out dim of first layer. default 32
  test_area: 5
  num_classes: 13 
  strides: [4, 4, 4, 4]
  nsample_conv: 24 
  nsample: 16 
  data_root: dataset/s3dis/trainval_fullarea
  voxel_size: 0.04
  voxel_max: 24000 
  loop: 30 

Model:
  architecture: [ # 2,3,4,7,3; decoder 
    'simple',
    'residual',
    'downsample',
    'residual',
    'residual',
    'residual',
    'downsample',
    'residual',
    'residual',
    'residual',
    'residual',
    'downsample',
    'residual',
    'residual',
    'residual',
    'residual',
    'residual',
    'residual',
    'residual',
    'downsample',
    'residual',
    'residual',
    'residual',
    'upsample',
    'diffusion_unit',
    'upsample',
    'diffusion_unit',
    'upsample',
    'diffusion_unit',
    'upsample',
    'diffusion_unit',
  ]
  
  
  convolution: 'dw_kpconv'
  decoder_out_dim: 32 
  bottleneck_ratio: 4 

TRAIN:
  arch: 'scene_seg_net' 
  aug: 'rot_scale_jit_cdrop_cont'
  use_xyz: True
  sync_bn: False 
  ignore_label: 255
  label_smoothing: 0.2
  # train_gpu: [0, 1, 2, 3]
  # workers: 40 
  # batch_size: 32
  # batch_size_val: 32
  train_gpu: [0]
  workers: 8 
  batch_size: 8 
  batch_size_val: 8
  base_lr: 0.01 
  epochs: 100 
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  drop_rate: 0.5
  manual_seed: 
  manual_seed: 
  print_freq: 30 
  save_freq: 1
  save_path:
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
Distributed:
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: True 
  world_size: 1
  rank: 0

TEST:
  test_list: dataset/s3dis/list/val5.txt
  test_list_full: dataset/s3dis/list/val5_full.txt
  split: val  # split in [train, val and test]
  test_gpu: [0]
  test_workers: 4
  batch_size_test: 4
  model_path:
  save_folder:
  names_path: data/s3dis/s3dis_names.txt
